/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: "us-east-2",
  aws_appsync_graphqlEndpoint:
    "https://3ctce77xgjbwvabr7y22qndqru.appsync-api.us-east-2.amazonaws.com/graphql",
  aws_appsync_region: "us-east-2",
  aws_appsync_authenticationType: "API_KEY",
  aws_appsync_apiKey: "da2-25adbnz4zffynki5wscvaxz6ca",
  aws_cloudfront_domain: "dfloplqh4uaf7.cloudfront.net",
};

export default awsmobile;
