name: Deploy Event Driven Architecture with DynamoDB, AppSync, Lambda, EventBridge and Step Functions
env:
  owner: SharjeelSafdar
  repo: project14c-virtual-lolly-app-event-driven

# Controls when the action will run. Triggers the workflow on
# 1) push event for main branch
# 2) pull_request generated on main branch
# 3) It's triggered only by changes in relavent files in backend/ directory
on:
  push:
    branch: [main]
    paths-ignore:
      - "README.md"
      - "client/**"
      - "backend/lib/p14c-frontend-deploy-stack.ts"
      - "backend/test/p14c-frontend-deploy-stack.test.ts"
      - "backend/utils/lambda/edgeLambda"
      - "backend/.gitignore"
      - "backend/.npmignore"
      - "backend/README.md"
      - "backend/P14c AWS Architecture.jpg"
      - ".github/workflows/deployFrontendBucketAndDist.yml"
      - ".github/workflows/deployGatsbyAppToS3.yml"
  pull_request:
    branch: [main]
    paths-ignore:
      - "README.md"
      - "client/**"
      - "backend/lib/p14c-frontend-deploy-stack.ts"
      - "backend/test/p14c-frontend-deploy-stack.test.ts"
      - "backend/utils/lambda/edgeLambda"
      - "backend/.gitignore"
      - "backend/.npmignore"
      - "backend/README.md"
      - "backend/P14c AWS Architecture.jpg"
      - ".github/workflows/deployFrontendBucketAndDist.yml"
      - ".github/workflows/deployGatsbyAppToS3.yml"

jobs:
  Deploy_Backend_Services:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout the Repository
        uses: actions/checkout@v2

      - name: Install NodeJS
        uses: actions/setup-node@v2
        with: { node-version: "14.15.0" }

      - name: Install Dependencies for CDK App
        uses: bahmutov/npm-install@v1
        with:
          working-directory: backend

      - name: Install Dependencies for GQL Lambda Function
        uses: bahmutov/npm-install@v1
        with:
          working-directory: backend/utils/lambda/gqlLambda

      - name: Install Dependencies for GitHub Lambda Function
        uses: bahmutov/npm-install@v1
        with:
          working-directory: backend/utils/lambda/githubLambda

      - name: Build CDK App with TypeScript Compiler
        working-directory: backend
        run: npm run build

      - name: Run Tests with Jest
        working-directory: backend
        run: npm run test test/p14c-backend-services-stack.test.ts

      - name: Deploy Backend-Services-Stack to AWS CloudFormation
        uses: docker://kikemnzz/automate-cdk-github-action-kmzz:v1.0.0
        with:
          cdk_version: 1.110.1
          cdk_action: deploy
          cdk_stack: P14cBackendServicesStack
          cdk_stack_directory: backend
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_PROJECT_REGION }}
